<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.Reporting" Version="2.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
		<PackageReference Include="System.Drawing.Common" Version="4.5.1" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="4.5.1" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="ClientDataSet.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ClientDataSet.xsd</DependentUpon>
		</Compile>
		<Compile Update="RptDataSets\Devis\DevisDataSet.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>DevisDataSet.xsd</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="ClientDataSet.xsd">
			<Generator>MSDataSetGenerator</Generator>
			<LastGenOutput>ClientDataSet.Designer.cs</LastGenOutput>
		</None>
		<None Update="RptDataSets\Devis\DevisDataSet.xsd">
		  <Generator>MSDataSetGenerator</Generator>
		  <LastGenOutput>DevisDataSet.Designer.cs</LastGenOutput>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="RptDataSets\Facture\" />
	  <Folder Include="RptModels\" />
	</ItemGroup>

</Project>
